import type { CastMember, CrewMember, Genre, MovieDetails, MovieReview } from "./types";

/**
 * Hand-curated catalog of real films used by the mock provider.
 * Metadata is accurate (year, runtime, director, genres); overviews are
 * original short synopses. `keywords` carry the "vibe" vocabulary that
 * drives deterministic mock embeddings — semantic search works offline.
 */

const G: Record<string, Genre> = {
  action: { id: 28, name: "Action" },
  adventure: { id: 12, name: "Adventure" },
  animation: { id: 16, name: "Animation" },
  comedy: { id: 35, name: "Comedy" },
  crime: { id: 80, name: "Crime" },
  drama: { id: 18, name: "Drama" },
  family: { id: 10751, name: "Family" },
  fantasy: { id: 14, name: "Fantasy" },
  history: { id: 36, name: "History" },
  horror: { id: 27, name: "Horror" },
  music: { id: 10402, name: "Music" },
  mystery: { id: 9648, name: "Mystery" },
  romance: { id: 10749, name: "Romance" },
  scifi: { id: 878, name: "Science Fiction" },
  thriller: { id: 53, name: "Thriller" },
  war: { id: 10752, name: "War" },
  western: { id: 37, name: "Western" },
};

interface Spec {
  id: number;
  title: string;
  year: number;
  date?: string; // full date if it matters (upcoming/now-playing)
  runtime: number;
  genres: (keyof typeof G)[];
  rating: number;
  pop: number;
  director: string;
  cast: string[];
  keywords: string[];
  overview: string;
  tagline?: string;
  lang?: string;
  budget?: number;
  revenue?: number;
  awards?: string[];
}

let castId = 10_000;
let crewId = 50_000;

function build(s: Spec): MovieDetails {
  const cast: CastMember[] = s.cast.map((name, i) => ({
    id: castId++,
    name,
    character: "",
    profilePath: null,
    order: i,
  }));
  const crew: CrewMember[] = [
    { id: crewId++, name: s.director, job: "Director", department: "Directing" },
  ];
  const reviews: MovieReview[] = REVIEW_BANK[s.id] ?? [];
  return {
    id: s.id,
    title: s.title,
    overview: s.overview,
    posterPath: null,
    backdropPath: null,
    releaseDate: s.date ?? `${s.year}-01-01`,
    voteAverage: s.rating,
    popularity: s.pop,
    genres: s.genres.map((g) => G[g]),
    runtime: s.runtime,
    tagline: s.tagline ?? null,
    budget: s.budget ?? 0,
    revenue: s.revenue ?? 0,
    originalLanguage: s.lang ?? "en",
    cast,
    crew,
    trailerKey: null,
    watchProviders: [],
    keywords: s.keywords,
    awards: s.awards ?? [],
    reviews,
  };
}

/** A few sample reviews for films where the review summarizer is showcased. */
const REVIEW_BANK: Record<number, MovieReview[]> = {
  157336: [
    { author: "orbitfan", rating: 9, createdAt: "2023-05-02", content: "The docking scene alone is worth the ticket. Emotionally it hits far harder than expected for a space film — the bookshelf sequence wrecked me." },
    { author: "cinephile_kt", rating: 7, createdAt: "2023-08-14", content: "Gorgeous and ambitious, though the exposition gets heavy in the middle act. Zimmer's organ score is doing a lot of lifting." },
    { author: "m.reyes", rating: 10, createdAt: "2024-01-20", content: "A film about parents and time disguised as a film about wormholes. The science mostly holds and the ending earns its sentimentality." },
  ],
  496243: [
    { author: "seoulcinema", rating: 10, createdAt: "2022-11-03", content: "A perfect machine of a screenplay. Shifts genre three times without ever losing you. The peach fuzz montage is master-class editing." },
    { author: "arthouse_al", rating: 9, createdAt: "2023-02-17", content: "Class warfare as farce, then as horror. The basement reveal recontextualizes everything before it." },
  ],
};

const SPECS: Spec[] = [
  // ---- Mind-bending sci-fi cluster ----
  { id: 157336, title: "Interstellar", year: 2014, runtime: 169, genres: ["scifi", "adventure", "drama"], rating: 8.4, pop: 96, director: "Christopher Nolan", cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"], keywords: ["space", "wormhole", "time-dilation", "father-daughter", "philosophical", "mind-bending", "emotional", "survival", "black-hole", "epic"], overview: "As Earth's crops fail, a pilot-turned-farmer joins a last-hope mission through a wormhole, where every hour on an alien ocean costs him years with his daughter.", tagline: "Mankind was born on Earth. It was never meant to die here.", budget: 165_000_000, revenue: 701_700_000, awards: ["Academy Award — Best Visual Effects"] },
  { id: 329865, title: "Arrival", year: 2016, runtime: 116, genres: ["scifi", "drama", "mystery"], rating: 7.9, pop: 74, director: "Denis Villeneuve", cast: ["Amy Adams", "Jeremy Renner", "Forest Whitaker"], keywords: ["aliens", "language", "linguistics", "time", "nonlinear", "philosophical", "melancholy", "mind-bending", "emotional", "first-contact"], overview: "A linguist is recruited to decode the language of visitors whose ships hang silently over twelve nations — and learns their grammar rewrites her sense of time.", awards: ["Academy Award — Best Sound Editing"] },
  { id: 27205, title: "Inception", year: 2010, runtime: 148, genres: ["scifi", "action", "thriller"], rating: 8.4, pop: 92, director: "Christopher Nolan", cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"], keywords: ["dreams", "heist", "subconscious", "mind-bending", "layered", "grief", "action", "puzzle", "ambiguous-ending"], overview: "A thief who steals secrets from dreams is offered a way home: plant an idea so deep in a sleeping mind that its owner believes it is his own.", tagline: "Your mind is the scene of the crime.", budget: 160_000_000, revenue: 836_800_000, awards: ["Academy Award — Best Cinematography"] },
  { id: 62, title: "2001: A Space Odyssey", year: 1968, runtime: 149, genres: ["scifi", "mystery"], rating: 8.1, pop: 45, director: "Stanley Kubrick", cast: ["Keir Dullea", "Gary Lockwood", "Douglas Rain"], keywords: ["space", "ai", "evolution", "monolith", "philosophical", "slow-burn", "mind-bending", "classic", "ambiguous-ending"], overview: "From a bone tossed skyward to a computer that will not open the pod bay doors, an enigmatic monolith steers humanity toward its next form." },
  { id: 335984, title: "Blade Runner 2049", year: 2017, runtime: 164, genres: ["scifi", "drama", "mystery"], rating: 7.6, pop: 68, director: "Denis Villeneuve", cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas"], keywords: ["dystopia", "ai", "identity", "neo-noir", "atmospheric", "slow-burn", "philosophical", "melancholy", "visually-stunning"], overview: "A replicant blade runner unearths a secret that blurs the line between born and made, and goes looking for the man who disappeared with the answer.", awards: ["Academy Award — Best Cinematography"] },
  { id: 286217, title: "The Martian", year: 2015, runtime: 144, genres: ["scifi", "adventure", "comedy"], rating: 7.7, pop: 71, director: "Ridley Scott", cast: ["Matt Damon", "Jessica Chastain", "Chiwetel Ejiofor"], keywords: ["space", "survival", "mars", "science", "optimistic", "funny", "problem-solving", "feel-good"], overview: "Stranded on Mars with disco music and a potato farm of his own devising, an astronaut refuses to die politely while NASA scrambles to bring him home." },
  { id: 264660, title: "Ex Machina", year: 2014, runtime: 108, genres: ["scifi", "thriller", "drama"], rating: 7.6, pop: 58, director: "Alex Garland", cast: ["Alicia Vikander", "Domhnall Gleeson", "Oscar Isaac"], keywords: ["ai", "consciousness", "manipulation", "isolation", "psychological", "slow-burn", "twist", "villain-wins", "unsettling"], overview: "A young coder wins a week at his reclusive CEO's estate to test whether a beautiful machine can think — without asking who is really being tested." },
  { id: 141, title: "Donnie Darko", year: 2001, runtime: 113, genres: ["scifi", "thriller", "drama"], rating: 7.7, pop: 44, director: "Richard Kelly", cast: ["Jake Gyllenhaal", "Jena Malone", "Mary McDonnell"], keywords: ["time-travel", "fate", "teenager", "surreal", "cult-classic", "mind-bending", "melancholy", "psychological", "ambiguous-ending"], overview: "After a jet engine falls on his bedroom, a troubled teenager follows a rabbit-suited prophet through twenty-eight days toward the end of the world." },
  { id: 1124, title: "The Prestige", year: 2006, runtime: 130, genres: ["drama", "mystery", "thriller"], rating: 8.2, pop: 60, director: "Christopher Nolan", cast: ["Christian Bale", "Hugh Jackman", "Scarlett Johansson"], keywords: ["magicians", "rivalry", "obsession", "twist", "mind-bending", "sacrifice", "victorian", "puzzle"], overview: "Two Victorian magicians turn a friendly rivalry into mutually assured destruction, each willing to give up everything for the perfect trick." },
  { id: 77, title: "Memento", year: 2000, runtime: 113, genres: ["mystery", "thriller"], rating: 8.2, pop: 52, director: "Christopher Nolan", cast: ["Guy Pearce", "Carrie-Anne Moss", "Joe Pantoliano"], keywords: ["memory", "revenge", "nonlinear", "puzzle", "mind-bending", "neo-noir", "unreliable-narrator", "twist"], overview: "Unable to form new memories, a man hunts his wife's killer using tattoos and Polaroids — told backwards, so you know exactly as little as he does." },
  { id: 603, title: "The Matrix", year: 1999, runtime: 136, genres: ["scifi", "action"], rating: 8.2, pop: 88, director: "Lana & Lilly Wachowski", cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"], keywords: ["simulation", "ai", "chosen-one", "dystopia", "action", "mind-bending", "cyberpunk", "classic"], overview: "A programmer learns his whole world is a simulation run by machines, and that the glitch he has always felt has a name: the Matrix.", tagline: "Free your mind.", budget: 63_000_000, revenue: 463_500_000, awards: ["Academy Award — Best Visual Effects"] },
  { id: 693134, title: "Dune: Part Two", year: 2024, date: "2024-03-01", runtime: 167, genres: ["scifi", "adventure"], rating: 8.2, pop: 85, director: "Denis Villeneuve", cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"], keywords: ["desert", "prophecy", "epic", "politics", "war", "visually-stunning", "world-building", "revenge"], overview: "Embraced by the Fremen as a prophet he does not want to be, Paul Atreides rides the desert's fury toward a throne — and a holy war he can see coming.", budget: 190_000_000, revenue: 714_400_000 },
  { id: 264, title: "Moon", year: 2009, runtime: 97, genres: ["scifi", "drama"], rating: 7.6, pop: 38, director: "Duncan Jones", cast: ["Sam Rockwell", "Kevin Spacey"], keywords: ["space", "isolation", "identity", "ai", "twist", "melancholy", "underrated", "slow-burn", "philosophical"], overview: "Three years alone on a lunar mining base, two weeks from home, Sam Bell meets the one person he never expected: himself." },
  { id: 686, title: "Contact", year: 1997, runtime: 150, genres: ["scifi", "drama", "mystery"], rating: 7.4, pop: 40, director: "Robert Zemeckis", cast: ["Jodie Foster", "Matthew McConaughey"], keywords: ["space", "first-contact", "faith", "science", "philosophical", "emotional", "father-daughter", "wonder"], overview: "A radio astronomer who has listened to the sky her whole life finally hears something back — a signal carrying blueprints for a machine with one seat." },
  { id: 428078, title: "Ad Astra", year: 2019, runtime: 123, genres: ["scifi", "drama"], rating: 6.1, pop: 42, director: "James Gray", cast: ["Brad Pitt", "Tommy Lee Jones"], keywords: ["space", "father-son", "isolation", "melancholy", "slow-burn", "psychological", "atmospheric"], overview: "An astronaut famous for his calm pulse travels to the edge of the solar system to find the father whose silence shaped him." },
  { id: 152601, title: "Her", year: 2013, runtime: 126, genres: ["romance", "scifi", "drama"], rating: 7.9, pop: 55, director: "Spike Jonze", cast: ["Joaquin Phoenix", "Scarlett Johansson", "Amy Adams"], keywords: ["ai", "loneliness", "love", "future", "melancholy", "sad-romance", "philosophical", "tender", "bittersweet"], overview: "A lonely letter-writer falls for his operating system, and the relationship is realer — and more heartbreaking — than anyone expects.", awards: ["Academy Award — Best Original Screenplay"] },
  { id: 38, title: "Eternal Sunshine of the Spotless Mind", year: 2004, runtime: 108, genres: ["romance", "scifi", "drama"], rating: 8.1, pop: 57, director: "Michel Gondry", cast: ["Jim Carrey", "Kate Winslet", "Kirsten Dunst"], keywords: ["memory", "love", "breakup", "surreal", "sad-romance", "melancholy", "mind-bending", "bittersweet", "nonlinear"], overview: "After learning his ex erased him from her memory, Joel books the same procedure — then changes his mind halfway through, with her fading around him.", awards: ["Academy Award — Best Original Screenplay"] },
  { id: 335983, title: "Annihilation", year: 2018, runtime: 115, genres: ["scifi", "horror", "mystery"], rating: 6.9, pop: 46, director: "Alex Garland", cast: ["Natalie Portman", "Jennifer Jason Leigh", "Tessa Thompson"], keywords: ["mutation", "expedition", "cosmic-horror", "unsettling", "surreal", "grief", "atmospheric", "mind-bending"], overview: "Five scientists walk into a shimmer where biology refracts like light. What comes out is not quite what went in." },
  { id: 419704, title: "Coherence", year: 2013, runtime: 89, genres: ["scifi", "thriller", "mystery"], rating: 7.0, pop: 22, director: "James Ward Byrkit", cast: ["Emily Baldoni", "Maury Sterling"], keywords: ["parallel-universe", "dinner-party", "low-budget", "puzzle", "mind-bending", "underrated", "paranoia", "twist"], overview: "A comet passes over a dinner party and the lights go out — in this house, and in the identical house down the street where the same friends are dining." },
  { id: 1585, title: "Primer", year: 2004, runtime: 77, genres: ["scifi", "thriller"], rating: 6.9, pop: 18, director: "Shane Carruth", cast: ["Shane Carruth", "David Sullivan"], keywords: ["time-travel", "engineers", "low-budget", "puzzle", "mind-bending", "underrated", "paradox", "dense"], overview: "Two engineers build something in a garage that should not work. It works. The flowcharts required to follow what happens next are part of the fun." },

  // ---- Crime / thriller ----
  { id: 155, title: "The Dark Knight", year: 2008, runtime: 152, genres: ["action", "crime", "drama"], rating: 8.5, pop: 94, director: "Christopher Nolan", cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"], keywords: ["batman", "chaos", "morality", "villain", "crime", "dark", "iconic", "escalation"], overview: "Gotham's white knight, its dark one, and a man who just wants to watch the world burn collide in a war for the city's soul.", tagline: "Why so serious?", budget: 185_000_000, revenue: 1_006_000_000, awards: ["Academy Award — Best Supporting Actor (Heath Ledger)"] },
  { id: 496243, title: "Parasite", year: 2019, runtime: 132, genres: ["thriller", "drama", "comedy"], rating: 8.5, pop: 80, director: "Bong Joon-ho", cast: ["Song Kang-ho", "Choi Woo-shik", "Park So-dam"], keywords: ["class", "family", "satire", "twist", "dark-comedy", "korean", "genre-shifting", "oscar-winner", "villain-wins"], overview: "One family of grifters folds itself into the household of one family of the oblivious rich — until something scratches back from under the floor.", lang: "ko", budget: 11_400_000, revenue: 258_800_000, awards: ["Academy Award — Best Picture", "Academy Award — Best Director", "Palme d'Or"] },
  { id: 680, title: "Pulp Fiction", year: 1994, runtime: 154, genres: ["crime", "thriller"], rating: 8.5, pop: 78, director: "Quentin Tarantino", cast: ["John Travolta", "Samuel L. Jackson", "Uma Thurman"], keywords: ["nonlinear", "hitmen", "dialogue", "dark-comedy", "cult-classic", "crime", "iconic"], overview: "Hitmen, a boxer, a briefcase, and a five-dollar shake orbit each other in interlocking stories told gloriously out of order.", awards: ["Academy Award — Best Original Screenplay", "Palme d'Or"] },
  { id: 807, title: "Se7en", year: 1995, runtime: 127, genres: ["crime", "mystery", "thriller"], rating: 8.4, pop: 66, director: "David Fincher", cast: ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow"], keywords: ["serial-killer", "sins", "dark", "rain", "bleak", "twist", "villain-wins", "detective", "unsettling"], overview: "A retiring detective and his replacement chase a killer who preaches through corpses — and saves his masterpiece for the ending.", tagline: "Seven deadly sins. Seven ways to die." },
  { id: 550, title: "Fight Club", year: 1999, runtime: 139, genres: ["drama", "thriller"], rating: 8.4, pop: 76, director: "David Fincher", cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"], keywords: ["identity", "consumerism", "twist", "anarchy", "cult-classic", "dark", "unreliable-narrator", "psychological"], overview: "An insomniac office drone and a soap salesman start a club with famous rules. The first one is not the one that matters." },
  { id: 210577, title: "Gone Girl", year: 2014, runtime: 149, genres: ["mystery", "thriller", "drama"], rating: 7.9, pop: 62, director: "David Fincher", cast: ["Ben Affleck", "Rosamund Pike", "Carrie Coon"], keywords: ["marriage", "media", "twist", "manipulation", "psychological", "villain-wins", "unreliable-narrator", "dark"], overview: "On their fifth anniversary, Amy Dunne disappears and her husband smiles at the wrong moment. Amazing Amy always did know how to write a story." },
  { id: 500, title: "Reservoir Dogs", year: 1992, runtime: 99, genres: ["crime", "thriller"], rating: 8.1, pop: 45, director: "Quentin Tarantino", cast: ["Harvey Keitel", "Tim Roth", "Steve Buscemi"], keywords: ["heist", "betrayal", "dialogue", "nonlinear", "violence", "cult-classic", "paranoia"], overview: "A diamond heist goes wrong offscreen; the movie is the warehouse afterward, where color-coded strangers work out which of them is a cop." },
  { id: 240, title: "The Godfather Part II", year: 1974, runtime: 202, genres: ["crime", "drama"], rating: 8.6, pop: 58, director: "Francis Ford Coppola", cast: ["Al Pacino", "Robert De Niro", "Robert Duvall"], keywords: ["mafia", "family", "power", "corruption", "epic", "classic", "tragedy", "parallel-timelines"], overview: "As young Vito builds an empire from Little Italy's streets, his son Michael freezes into it — winning everything and losing everyone.", awards: ["Academy Award — Best Picture"] },
  { id: 238, title: "The Godfather", year: 1972, runtime: 175, genres: ["crime", "drama"], rating: 8.7, pop: 70, director: "Francis Ford Coppola", cast: ["Marlon Brando", "Al Pacino", "James Caan"], keywords: ["mafia", "family", "power", "succession", "classic", "epic", "tragedy", "iconic"], overview: "The reluctant son of an aging don is pulled into the family business one favor, one funeral, one baptism at a time.", tagline: "An offer you can't refuse.", budget: 6_000_000, revenue: 245_000_000, awards: ["Academy Award — Best Picture"] },
  { id: 111, title: "Scarface", year: 1983, runtime: 170, genres: ["crime", "drama"], rating: 8.1, pop: 50, director: "Brian De Palma", cast: ["Al Pacino", "Michelle Pfeiffer"], keywords: ["rise-and-fall", "drugs", "ambition", "excess", "miami", "tragedy", "iconic", "violence"], overview: "A Cuban refugee claws his way to the top of Miami's cocaine trade, where the world is his — briefly." },
  { id: 4547, title: "No Country for Old Men", year: 2007, runtime: 122, genres: ["crime", "thriller", "western"], rating: 8.0, pop: 48, director: "Joel & Ethan Coen", cast: ["Javier Bardem", "Josh Brolin", "Tommy Lee Jones"], keywords: ["fate", "cat-and-mouse", "villain-wins", "bleak", "slow-burn", "atmospheric", "coin-toss", "neo-western"], overview: "A hunter finds two million dollars in the desert; what finds him carries a cattle gun and a coin. Call it.", awards: ["Academy Award — Best Picture"] },
  { id: 27428, title: "Oldboy", year: 2003, runtime: 120, genres: ["thriller", "mystery", "action"], rating: 8.3, pop: 47, director: "Park Chan-wook", cast: ["Choi Min-sik", "Yoo Ji-tae"], keywords: ["revenge", "imprisonment", "twist", "korean", "dark", "villain-wins", "hammer", "tragedy", "unsettling"], overview: "Released after fifteen unexplained years in a private cell, Oh Dae-su gets five days to find out why — and learns the prison was the mercy.", lang: "ko" },
  { id: 106646, title: "The Wolf of Wall Street", year: 2013, runtime: 180, genres: ["crime", "comedy", "drama"], rating: 8.0, pop: 65, director: "Martin Scorsese", cast: ["Leonardo DiCaprio", "Jonah Hill", "Margot Robbie"], keywords: ["excess", "fraud", "wall-street", "dark-comedy", "rise-and-fall", "funny", "energetic"], overview: "Penny stocks, quaaludes, and a yacht in a storm: the confessions of a broker who sold everything, mostly to himself." },

  // ---- Feel-good / funny-but-emotional ----
  { id: 496, title: "Amélie", year: 2001, runtime: 122, genres: ["comedy", "romance"], rating: 7.9, pop: 49, director: "Jean-Pierre Jeunet", cast: ["Audrey Tautou", "Mathieu Kassovitz"], keywords: ["whimsical", "paris", "kindness", "shy", "feel-good", "charming", "romantic", "quirky"], overview: "A shy Montmartre waitress secretly engineers small miracles for strangers, until her own happiness becomes the one scheme she can't execute.", lang: "fr" },
  { id: 13, title: "Forrest Gump", year: 1994, runtime: 142, genres: ["drama", "romance", "comedy"], rating: 8.5, pop: 72, director: "Robert Zemeckis", cast: ["Tom Hanks", "Robin Wright", "Gary Sinise"], keywords: ["life-story", "innocence", "history", "feel-good", "emotional", "funny-but-emotional", "love", "classic"], overview: "A slow-running, fast-loving Alabama boy drifts through three decades of American history, changing it by accident and missing only one thing on purpose.", awards: ["Academy Award — Best Picture"] },
  { id: 620, title: "Ghostbusters", year: 1984, runtime: 105, genres: ["comedy", "fantasy"], rating: 7.5, pop: 41, director: "Ivan Reitman", cast: ["Bill Murray", "Dan Aykroyd", "Sigourney Weaver"], keywords: ["ghosts", "new-york", "funny", "classic", "quotable", "feel-good", "supernatural"], overview: "Three fired parapsychologists go into pest control for the recently deceased, just as something older than the city starts renting the top floor." },
  { id: 20342, title: "Little Miss Sunshine", year: 2006, runtime: 101, genres: ["comedy", "drama"], rating: 7.7, pop: 36, director: "Jonathan Dayton & Valerie Faris", cast: ["Abigail Breslin", "Steve Carell", "Toni Collette"], keywords: ["road-trip", "dysfunctional-family", "funny-but-emotional", "feel-good", "quirky", "bittersweet", "underdog", "family"], overview: "Six fraying relatives push a yellow VW bus across three states so a seven-year-old can dance like nobody's watching. Everybody watches." },
  { id: 773, title: "Little Women", year: 2019, runtime: 135, genres: ["drama", "romance"], rating: 7.9, pop: 43, director: "Greta Gerwig", cast: ["Saoirse Ronan", "Florence Pugh", "Timothée Chalamet"], keywords: ["sisters", "ambition", "period", "warm", "emotional", "nonlinear", "feel-good", "bittersweet"], overview: "Four sisters rehearse their futures in a Massachusetts attic; years later, Jo tries to write an ending the world will let her keep." },
  { id: 10681, title: "WALL·E", year: 2008, runtime: 98, genres: ["animation", "family", "scifi"], rating: 8.1, pop: 63, director: "Andrew Stanton", cast: ["Ben Burtt", "Elissa Knight"], keywords: ["robot", "love", "environment", "wordless", "feel-good", "family", "tender", "space", "charming"], overview: "The last robot on Earth spends his days compacting trash and collecting treasures — until a sleek probe named EVE gives him a directive of his own.", awards: ["Academy Award — Best Animated Feature"] },
  { id: 14160, title: "Up", year: 2009, runtime: 96, genres: ["animation", "family", "adventure"], rating: 7.9, pop: 61, director: "Pete Docter", cast: ["Ed Asner", "Jordan Nagai"], keywords: ["grief", "adventure", "balloons", "funny-but-emotional", "family", "feel-good", "tearjerker", "friendship"], overview: "A widower ties ten thousand balloons to his house and floats toward a promise — with a Wilderness Explorer stowed away on the porch.", awards: ["Academy Award — Best Animated Feature"] },
  { id: 508442, title: "Soul", year: 2020, runtime: 100, genres: ["animation", "family", "fantasy"], rating: 8.1, pop: 54, director: "Pete Docter", cast: ["Jamie Foxx", "Tina Fey"], keywords: ["jazz", "purpose", "afterlife", "philosophical", "feel-good", "funny-but-emotional", "family", "music", "tender"], overview: "On the day of his big break, a jazz pianist falls down a manhole and into the place where souls get their spark — arguing the whole way back.", awards: ["Academy Award — Best Animated Feature"] },
  { id: 490132, title: "Green Book", year: 2018, runtime: 130, genres: ["drama", "comedy"], rating: 8.2, pop: 46, director: "Peter Farrelly", cast: ["Viggo Mortensen", "Mahershala Ali"], keywords: ["road-trip", "friendship", "1960s", "feel-good", "funny-but-emotional", "music", "odd-couple"], overview: "A Bronx bouncer drives a virtuoso pianist through the Deep South of 1962, and an employment arrangement becomes something neither man had a word for.", awards: ["Academy Award — Best Picture"] },
  { id: 637, title: "Life Is Beautiful", year: 1997, runtime: 116, genres: ["comedy", "drama", "war"], rating: 8.5, pop: 44, director: "Roberto Benigni", cast: ["Roberto Benigni", "Nicoletta Braschi"], keywords: ["holocaust", "father-son", "funny-but-emotional", "tearjerker", "sacrifice", "love", "bittersweet"], overview: "A relentlessly playful waiter turns a concentration camp into a game with a thousand points and a tank for the prize, to keep his son from seeing the truth.", lang: "it", awards: ["Academy Award — Best Actor"] },
  { id: 424694, title: "Paddington 2", year: 2017, runtime: 103, genres: ["family", "comedy", "adventure"], rating: 7.8, pop: 39, director: "Paul King", cast: ["Ben Whishaw", "Hugh Grant", "Sally Hawkins"], keywords: ["kindness", "family", "feel-good", "charming", "funny", "wholesome", "prison", "marmalade"], overview: "A very polite bear is framed for the theft of a pop-up book and proceeds to reform an entire prison with marmalade and good manners." },
  { id: 22881, title: "The Blind Side", year: 2009, runtime: 129, genres: ["drama"], rating: 7.6, pop: 33, director: "John Lee Hancock", cast: ["Sandra Bullock", "Quinton Aaron"], keywords: ["sports", "family", "adoption", "feel-good", "underdog", "emotional"], overview: "A Memphis family takes in a homeless teenager with a protective instinct that turns out to be worth a football scholarship — and much more." },

  // ---- Anime / animation with world-building ----
  { id: 129, title: "Spirited Away", year: 2001, runtime: 125, genres: ["animation", "family", "fantasy"], rating: 8.5, pop: 77, director: "Hayao Miyazaki", cast: ["Rumi Hiiragi", "Miyu Irino"], keywords: ["anime", "spirits", "bathhouse", "world-building", "coming-of-age", "ghibli", "wonder", "family", "visually-stunning"], overview: "Moving-day detour: a sulky ten-year-old takes a wrong turn into a bathhouse for gods, loses her name, and works her way back to it.", lang: "ja", awards: ["Academy Award — Best Animated Feature"] },
  { id: 128, title: "Princess Mononoke", year: 1997, runtime: 134, genres: ["animation", "adventure", "fantasy"], rating: 8.3, pop: 56, director: "Hayao Miyazaki", cast: ["Yōji Matsuda", "Yuriko Ishida"], keywords: ["anime", "nature", "war", "gods", "world-building", "ghibli", "epic", "environment", "morally-complex"], overview: "Cursed by a dying boar god, a prince rides west into a war between iron and forest where neither side is wrong enough to root against.", lang: "ja" },
  { id: 372058, title: "Your Name", year: 2016, runtime: 106, genres: ["animation", "romance", "fantasy"], rating: 8.5, pop: 69, director: "Makoto Shinkai", cast: ["Ryunosuke Kamiki", "Mone Kamishiraishi"], keywords: ["anime", "body-swap", "comet", "time", "sad-romance", "emotional", "visually-stunning", "bittersweet", "longing"], overview: "A Tokyo boy and a small-town girl keep waking up in each other's bodies — then the swapping stops, and he goes looking for a town that isn't there.", lang: "ja" },
  { id: 149, title: "Akira", year: 1988, runtime: 124, genres: ["animation", "scifi", "action"], rating: 8.0, pop: 48, director: "Katsuhiro Otomo", cast: ["Mitsuo Iwata", "Nozomu Sasaki"], keywords: ["anime", "cyberpunk", "psychic", "dystopia", "world-building", "iconic", "body-horror", "neo-tokyo"], overview: "In Neo-Tokyo, a biker gang kid develops powers the government has killed to contain before — and his best friend is the only one who can reach him.", lang: "ja" },
  { id: 378064, title: "A Silent Voice", year: 2016, runtime: 130, genres: ["animation", "drama", "romance"], rating: 8.1, pop: 51, director: "Naoko Yamada", cast: ["Miyu Irino", "Saori Hayami"], keywords: ["anime", "bullying", "redemption", "deafness", "emotional", "sad-romance", "tearjerker", "forgiveness", "tender"], overview: "Years after driving a deaf classmate out of school, a friendless teenager learns sign language for one reason: to say sorry properly.", lang: "ja" },
  { id: 4935, title: "Howl's Moving Castle", year: 2004, runtime: 119, genres: ["animation", "fantasy", "romance"], rating: 8.4, pop: 64, director: "Hayao Miyazaki", cast: ["Chieko Baisho", "Takuya Kimura"], keywords: ["anime", "curse", "wizard", "world-building", "ghibli", "romantic", "war", "charming", "wonder"], overview: "Cursed into old age by a jealous witch, a young hatmaker keeps house for a vain wizard in a walking castle held together by a fire demon's bargain.", lang: "ja" },
  { id: 569094, title: "Spider-Man: Across the Spider-Verse", year: 2023, runtime: 140, genres: ["animation", "action", "adventure"], rating: 8.4, pop: 79, director: "Joaquim Dos Santos", cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac"], keywords: ["multiverse", "superhero", "visually-stunning", "world-building", "coming-of-age", "family", "energetic", "cliffhanger"], overview: "Miles Morales crashes a multiversal society of Spider-People and discovers the one canon event they will not let him break: his own story." },
  { id: 916224, title: "Suzume", year: 2022, runtime: 122, genres: ["animation", "adventure", "fantasy"], rating: 7.8, pop: 47, director: "Makoto Shinkai", cast: ["Nanoka Hara", "Hokuto Matsumura"], keywords: ["anime", "doors", "disaster", "grief", "road-trip", "emotional", "visually-stunning", "healing"], overview: "A girl chases a dwindling three-legged chair across Japan, closing doors that let disasters through — each one opening onto a grief of her own.", lang: "ja" },

  // ---- Horror / unsettling ----
  { id: 419430, title: "Get Out", year: 2017, runtime: 104, genres: ["horror", "thriller", "mystery"], rating: 7.6, pop: 59, director: "Jordan Peele", cast: ["Daniel Kaluuya", "Allison Williams"], keywords: ["social-horror", "racism", "twist", "unsettling", "satire", "hypnosis", "smart-horror"], overview: "Meeting the girlfriend's parents goes exactly as smoothly as promised — which is, in the end, the horrifying part.", awards: ["Academy Award — Best Original Screenplay"] },
  { id: 493922, title: "Hereditary", year: 2018, runtime: 127, genres: ["horror", "mystery", "thriller"], rating: 7.3, pop: 52, director: "Ari Aster", cast: ["Toni Collette", "Alex Wolff", "Milly Shapiro"], keywords: ["family", "grief", "cult", "dread", "unsettling", "slow-burn", "disturbing", "inheritance"], overview: "After the funeral of a secretive grandmother, a family discovers that what they inherited is not in the will." },
  { id: 447332, title: "A Quiet Place", year: 2018, runtime: 90, genres: ["horror", "thriller", "scifi"], rating: 7.4, pop: 57, director: "John Krasinski", cast: ["Emily Blunt", "John Krasinski", "Millicent Simmonds"], keywords: ["silence", "family", "monsters", "tension", "survival", "deafness", "suspense"], overview: "A family survives on a farm where sound is death, expecting a baby who does not know the rules yet." },
  { id: 694, title: "The Shining", year: 1980, runtime: 146, genres: ["horror", "thriller"], rating: 8.2, pop: 60, director: "Stanley Kubrick", cast: ["Jack Nicholson", "Shelley Duvall"], keywords: ["hotel", "isolation", "madness", "classic", "dread", "unsettling", "winter", "iconic"], overview: "A winter caretaker brings his family to an empty mountain hotel to write. The hotel has other work for him." },
  { id: 1933, title: "The Others", year: 2001, runtime: 104, genres: ["horror", "mystery", "thriller"], rating: 7.6, pop: 35, director: "Alejandro Amenábar", cast: ["Nicole Kidman", "Fionnula Flanagan"], keywords: ["ghosts", "twist", "gothic", "atmospheric", "slow-burn", "unsettling", "period"], overview: "In a fog-wrapped island mansion, a mother of two photosensitive children becomes certain the house is occupied by intruders she cannot see." },

  // ---- Drama / prestige ----
  { id: 278, title: "The Shawshank Redemption", year: 1994, runtime: 142, genres: ["drama", "crime"], rating: 8.7, pop: 82, director: "Frank Darabont", cast: ["Tim Robbins", "Morgan Freeman"], keywords: ["prison", "hope", "friendship", "patience", "classic", "emotional", "feel-good", "iconic"], overview: "A banker serving two life sentences spends nineteen years proving that hope is not the dangerous thing his friend says it is.", tagline: "Fear can hold you prisoner. Hope can set you free." },
  { id: 424, title: "Schindler's List", year: 1993, runtime: 195, genres: ["drama", "history", "war"], rating: 8.6, pop: 55, director: "Steven Spielberg", cast: ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley"], keywords: ["holocaust", "war", "sacrifice", "history", "tearjerker", "classic", "black-and-white"], overview: "A war profiteer's factory ledger slowly becomes the only thing standing between eleven hundred names and the trains east.", awards: ["Academy Award — Best Picture"] },
  { id: 244786, title: "Whiplash", year: 2014, runtime: 106, genres: ["drama", "music"], rating: 8.4, pop: 67, director: "Damien Chazelle", cast: ["Miles Teller", "J.K. Simmons"], keywords: ["jazz", "obsession", "mentor", "ambition", "intense", "music", "abuse", "electric-ending"], overview: "A conservatory drummer and a conductor who throws chairs push each other past every line that separates greatness from destruction — assuming there is one.", awards: ["Academy Award — Best Supporting Actor"] },
  { id: 313369, title: "La La Land", year: 2016, runtime: 128, genres: ["romance", "drama", "music"], rating: 7.9, pop: 66, director: "Damien Chazelle", cast: ["Ryan Gosling", "Emma Stone"], keywords: ["musical", "dreams", "los-angeles", "sad-romance", "bittersweet", "jazz", "what-if", "romantic"], overview: "An actress and a jazz purist fall in love in a city that asks them to choose between each other and the reason they came.", awards: ["Academy Award — Best Director"] },
  { id: 598, title: "City of God", year: 2002, runtime: 130, genres: ["crime", "drama"], rating: 8.4, pop: 53, director: "Fernando Meirelles", cast: ["Alexandre Rodrigues", "Leandro Firmino"], keywords: ["favela", "gangs", "photography", "coming-of-age", "violence", "brazilian", "kinetic", "tragedy"], overview: "In a Rio favela where boys inherit guns like surnames, one kid aims a camera instead — and lives long enough to develop the film.", lang: "pt" },
  { id: 76203, title: "12 Years a Slave", year: 2013, runtime: 134, genres: ["drama", "history"], rating: 8.0, pop: 41, director: "Steve McQueen", cast: ["Chiwetel Ejiofor", "Michael Fassbender", "Lupita Nyong'o"], keywords: ["slavery", "history", "survival", "harrowing", "true-story", "unflinching"], overview: "A free violinist from New York wakes in chains with a new name, and holds onto his own for twelve years.", awards: ["Academy Award — Best Picture"] },
  { id: 872585, title: "Oppenheimer", year: 2023, runtime: 180, genres: ["drama", "history", "thriller"], rating: 8.1, pop: 83, director: "Christopher Nolan", cast: ["Cillian Murphy", "Emily Blunt", "Robert Downey Jr."], keywords: ["atomic-bomb", "physics", "guilt", "history", "nonlinear", "epic", "biopic", "morally-complex"], overview: "The man who gave humanity the means to end itself spends the rest of his life in the blast radius of that decision.", budget: 100_000_000, revenue: 975_800_000, awards: ["Academy Award — Best Picture"] },
  { id: 546554, title: "Knives Out", year: 2019, runtime: 130, genres: ["mystery", "comedy", "crime"], rating: 7.8, pop: 63, director: "Rian Johnson", cast: ["Daniel Craig", "Ana de Armas", "Chris Evans"], keywords: ["whodunit", "family", "inheritance", "funny", "twist", "cozy-mystery", "satire", "ensemble"], overview: "A mystery novelist dies after his own birthday party, and a drawling detective finds a family where everyone has a motive and one nurse cannot lie." },
  { id: 361743, title: "Top Gun: Maverick", year: 2022, runtime: 130, genres: ["action", "drama"], rating: 8.2, pop: 75, director: "Joseph Kosinski", cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly"], keywords: ["aviation", "legacy", "mentor", "spectacle", "crowd-pleaser", "feel-good", "practical-effects"], overview: "Thirty years past his own graduation, the Navy's most decorated insubordinate must teach the next generation a mission he is not supposed to fly." },
  { id: 634649, title: "Spider-Man: No Way Home", year: 2021, runtime: 148, genres: ["action", "adventure", "scifi"], rating: 7.9, pop: 81, director: "Jon Watts", cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch"], keywords: ["multiverse", "superhero", "nostalgia", "sacrifice", "crowd-pleaser", "emotional"], overview: "With his identity exposed, Peter Parker asks for a spell to make the world forget — and tears a hole every other universe's villains climb through." },

  // ---- Family night ----
  { id: 585, title: "Monsters, Inc.", year: 2001, runtime: 92, genres: ["animation", "family", "comedy"], rating: 8.0, pop: 58, director: "Pete Docter", cast: ["John Goodman", "Billy Crystal"], keywords: ["monsters", "family", "funny", "feel-good", "friendship", "wholesome", "charming"], overview: "The top scarer at Monsters, Incorporated discovers the one thing more powerful than a child's scream — and it comes attached to a toddler named Boo." },
  { id: 8587, title: "The Lion King", year: 1994, runtime: 88, genres: ["animation", "family", "drama"], rating: 8.3, pop: 71, director: "Roger Allers & Rob Minkoff", cast: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones"], keywords: ["family", "succession", "africa", "classic", "music", "coming-of-age", "tragedy", "feel-good"], overview: "A lion cub grows up believing he killed his father — hakuna matata only works until the past comes looking." },
  { id: 109445, title: "Frozen", year: 2013, runtime: 102, genres: ["animation", "family", "fantasy"], rating: 7.3, pop: 62, director: "Chris Buck & Jennifer Lee", cast: ["Kristen Bell", "Idina Menzel"], keywords: ["sisters", "ice", "music", "family", "feel-good", "love", "musical"], overview: "The act of true love that thaws a frozen kingdom turns out not to be the kiss everyone — including the movie — expected.", awards: ["Academy Award — Best Animated Feature"] },
  { id: 671, title: "Harry Potter and the Philosopher's Stone", year: 2001, runtime: 152, genres: ["fantasy", "adventure", "family"], rating: 7.9, pop: 74, director: "Chris Columbus", cast: ["Daniel Radcliffe", "Emma Watson", "Rupert Grint"], keywords: ["magic", "school", "friendship", "world-building", "family", "wonder", "classic", "chosen-one"], overview: "The boy in the cupboard under the stairs gets a letter, a wand, and the first birthday cake of his life — hagrid may have sat on it." },
  { id: 620683, title: "The Mitchells vs. the Machines", year: 2021, runtime: 114, genres: ["animation", "family", "comedy", "scifi"], rating: 7.7, pop: 40, director: "Mike Rianda", cast: ["Abbi Jacobson", "Danny McBride", "Olivia Colman"], keywords: ["family", "road-trip", "robots", "ai", "funny", "feel-good", "father-daughter", "energetic"], overview: "The world's most dysfunctional family road-trips straight into the robot apocalypse, and turns out to be exactly the wrong kind of people to fight it. Which is right." },

  // ---- Upcoming / now playing (relative to app "now") ----
  { id: 1184918, title: "The Wild Robot", year: 2024, date: "2026-08-14", runtime: 102, genres: ["animation", "family", "scifi"], rating: 8.3, pop: 70, director: "Chris Sanders", cast: ["Lupita Nyong'o", "Pedro Pascal"], keywords: ["robot", "nature", "motherhood", "feel-good", "tearjerker", "family", "wonder", "tender"], overview: "A shipwrecked service robot reboots on an island with no one to serve, and adopts an orphaned gosling nobody programmed her to love." },
  { id: 933260, title: "The Substance", year: 2024, date: "2026-07-10", runtime: 141, genres: ["horror", "scifi", "thriller"], rating: 7.1, pop: 64, director: "Coralie Fargeat", cast: ["Demi Moore", "Margaret Qualley"], keywords: ["body-horror", "fame", "aging", "satire", "disturbing", "unsettling", "hollywood"], overview: "A fading star injects a black-market serum that generates a younger, better version of herself. The two of them are one — a fact only one of them respects." },
  { id: 999999, title: "Marathon of Light", year: 2026, date: "2026-09-25", runtime: 128, genres: ["scifi", "drama"], rating: 0, pop: 30, director: "Ana Reyes", cast: ["Ensemble cast"], keywords: ["space", "generation-ship", "epic", "upcoming", "philosophical"], overview: "Three generations aboard a slowing starship debate whether to finish a voyage none of them chose to begin. (Festival release — wide release this fall.)" },
];

export const MOCK_CATALOG: MovieDetails[] = SPECS.map(build);

export const MOCK_BY_ID = new Map(MOCK_CATALOG.map((m) => [m.id, m]));
